const answerActionTypes = {
  CREATE_ANSWER_START: "CREATE_ANSWER_START",
  CREATE_ANSWER_SUCCESS: "CREATE_ANSWER_SUCCESS",
  CREATE_ANSWER_FAILURE: "CREATE_ANSWER_FAILURE",
  FETCH_ANSWERS_START: "FETCH_ANSWERS_START",
  FETCH_ANSWERS_SUCCESS: "FETCH_ANSWERS_SUCCESS",
  FETCH_ANSWERS_FAILURE: "FETCH_ANSWERS_FAILURE",
  FETCH_GROUP_ANSWERS_START: "FETCH_GROUP_ANSWERS_START",
  FETCH_GROUP_ANSWERS_SUCCESS: "FETCH_GROUP_ANSWERS_SUCCESS",
  FETCH_GROUP_ANSWERS_FAILURE: "FETCH_GROUP_ANSWERS_FAILURE",
};

export default answerActionTypes;
