const questionActionTypes = {
  UPDATE_STATUS: "UPDATE_STATUS",
  FETCH_QUESTIONS_START: "FETCH_QUESTIONS_START",
  FETCH_QUESTIONS_SUCCESS: "FETCH_QUESTIONS_SUCCESS",
  FETCH_QUESTIONS_FAILURE: "FETCH_QUESTIONS_FAILURE",
  DOWNLOAD_INPUT_START: "DOWNLOAD_INPUT_START",
  DOWNLOAD_INPUT_SUCCESS: "DOWNLOAD_INPUT_SUCCESS",
  DOWNLOAD_INPUT_FAILURE: "DOWNLOAD_INPUT_FAILURE",
};

export const questionTypes = {
  MCQ: "mcq",
  MSQ: "msq",
  INPUT: "input",
};
export default questionActionTypes;
