const groupActionTypes = {
  FETCH_GROUP_START: "FETCH_GROUP_START",
  FETCH_GROUP_SUCCESS: "FETCH_GROUP_SUCCESS",
  FETCH_GROUP_FAILURE: "FETCH_GROUP_FAILURE",
  UPDATE_GROUP_START: "UPDATE_GROUP_START",
  UPDATE_GROUP_SUCCESS: "UPDATE_GROUP_SUCCESS",
  UPDATE_GROUP_FAILURE: "UPDATE_GROUP_FAILURE",
  TOGGLE_EDIT: "TOGGLE_EDIT",
};

export default groupActionTypes;
